### ISSUE TITLE
Some projects are missing from the project list in the settings

### ISSUE THREAD

**Issue by chandora** [pvisionjp/redsync#1]
**Describe the bug**
Some projects are missing from the project list in the settings dialogue.

**To Reproduce**
1. Open the settings
2. Specify URL and API Key
3. Open the pull-down for the projects

**Expected behavior**
All projects are listed.

**Screenshots**
N/A

**Environment (please complete the following information):**
 - Windows
 - Chrome

**Additional context**
From the network trace in the dev tool, there are 33 projects in Redmine, but there is a limit to 25 projects in the API call.

**Comment by chandora** [comment]
The limit is set to 100 and multiple reads are executed if needed.

**Comment by pvisionjp** [comment]
The limit is set to 100 and multiple reads are executed if more than 100 projects exist.
