### ISSUE TITLE
Setting of Include Issue ID in Card's Title disabled when using JSONP checked

### ISSUE THREAD

**Issue by chandora** [pvisionjp/redsync#23]
**Describe the bug**
In the settings window, the Include Issue ID in Card's Title check box is disabled when the Access using Jsonp is checked.

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Access using Jsonp'
3. See 'Include Issue ID in Card's Title' is disabled

**Expected behavior**
'Include Issue ID in Card's Title' is not disabled.

**Screenshots**
None

**Environment (please complete the following information):**
N/A

**Additional context**
None

**Comment by pvisionjp** [comment]
Fixed in 1.13.2
