### ISSUE TITLE
Gantt: The Gantt chart can be unlocked with JSONP enabled

### ISSUE THREAD

**Issue by chandora** [pvisionjp/redsync#26]
**Describe the bug**
The Gantt can be unlocked for editing when JSONP is enabled in Settings.

**To Reproduce**
1. Enable JSONP in Settings
2. Open the Gantt chart and unlock for editing
3. See error

**Expected behavior**
The Gantt chart should not be unlocked when JSONP is enabled.

**Screenshots**
None

**Environment (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Additional context**
None

**Comment by pvisionjp** [comment]
Fixed in 1.13.2
