### ISSUE TITLE
Gantt: Issue bar not updated when changing due date to same as start date

### ISSUE THREAD

**Issue by chandora** [pvisionjp/redsync#27]
**Describe the bug**
When I change the due date by dragging the end edge of the issue bar to the same date as the start date, the due date is not updated.

**To Reproduce**
1. Open the Gantt chart
2. Drag the due date to the same date as the start date
3. See error

**Expected behavior**
The due date is changed to the same date as the start date and it becomes a milestone.

**Screenshots**
None

**Environment (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Additional context**
None

**Comment by pvisionjp** [comment]
Fixed in 1.13.2
