### ISSUE TITLE
Gantt: Date label invalid when a milestone bar clicked

### ISSUE THREAD

**Issue by chandora** [pvisionjp/redsync#28]
**Describe the bug**
When a milestone bar (start and due dates are the same) is clicked, the displayed date label has an invalid expression (NaNa/NaNa/NaNa).

**To Reproduce**
1. Open the Gantt chart
2. Click on a milestone bar
3. See error

**Expected behavior**
The data label should be displayed with the correct date expression.

**Screenshots**
None

**Environment (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Additional context**
None

**Comment by pvisionjp** [comment]
Fixed in 1.13.2
