### ISSUE TITLE
Gantt:  Additional blank lines (issue bars) after changing 'include close issue' flag

### ISSUE THREAD

**Issue by chandora** [pvisionjp/redsync#30]
**Describe the bug**
Additional blank lines (issue bars) are displayed after changing the 'Include close issue' flag on the setting.

**To Reproduce**
1. Go to 'Gantt'
2. Click on the 'settings' icon
3. Check/uncheck the 'Include close issue' flag
4. See the error

**Expected behavior**
Blank lines should not be displayed.

**Screenshots**

**Environment (please complete the following information):**

**Additional context**

**Comment by pvisionjp** [comment]
Fixed in 1.14.2
