### ISSUE TITLE
Gantt: Incorrect bar displayed when start date missing

### ISSUE THREAD

**Issue by chandora** [pvisionjp/redsync#32]
**Describe the bug**
When the start date is missing in an issue, the Bar for the issue on the Gantt chart is not displayed correctly.

**To Reproduce**
1. Create an issue without the start date
2. Open the Gantt chart
5. See the error

**Expected behavior**
The issue should be displayed as a milestone

**Screenshots**
None

**Environment (please complete the following information):**

**Additional context**

**Comment by pvisionjp** [comment]
Supported in 1.15.0
