### ISSUE TITLE
Gantt: No milestone when start and due dates are same

### ISSUE THREAD

**Issue by chandora** [pvisionjp/redsync#33]
**Describe the bug**
Bar on the Gantt chart is displayed as a standard task when the start and due dates are the same.

**To Reproduce**
1. Create an issue with the same start and due dates
2. Open the Gantt chart
3. See the error

**Expected behavior**
The Bar should be displayed as a milestone.

**Screenshots**
None

**Environment (please complete the following information):**

**Additional context**

**Comment by pvisionjp** [comment]
It can be a one-day task or a milestone.
To distinguish them, a task with either a start date or a due date only should be regarded as a milestone.
