### ISSUE TITLE
Sync: Unnecessary update during Sync with Redmine

### ISSUE THREAD

**Issue by chandora** [pvisionjp/redsync#34]
**Describe the bug**
Sync with Redmine updates issues that have not been changed. The issues have null for start or due date.

**To Reproduce**
1. Create an issue without a start or due date on Redmine.
2. Sync with Redmine.
3. Sync with Redmine again without any update.
4. Stat dialog says it is updating issues.

**Expected behavior**
It should not update issues without change.

**Screenshots**
None

**Environment (please complete the following information):**

**Additional context**

**Comment by pvisionjp** [comment]
Fixed in 1.15.1
