### ISSUE TITLE
Sync: Links not included when exclude links flags cleared in the settings

### ISSUE THREAD

**Issue by chandora** [pvisionjp/redsync#35]
**Describe the bug**
Sync with Redmine does not include the links to children/relations when the exclude links to children/relations flags in the settings are cleared, 

**To Reproduce**
1. Set the flags (exclude links ...)
2. Execute Sync with Redmine
3. Confirm cards do not have links to children/relations
4. Clear the flags
5. Execute Sync with Redmine
6. Check if cards have links to children/relations

**Expected behavior**
Cards should have links to children/relations if applicable.

**Screenshots**
None

**Environment (please complete the following information):**

**Additional context**

**Comment by pvisionjp** [comment]
Fixed in 1.15.1
