### ISSUE TITLE
Gantt: Overlapped task node in the task tree when a task moved from under the root to another task

### ISSUE THREAD

**Issue by chandora** [pvisionjp/redsync#36]
**Describe the bug**
A node in the task tree is overlapped when a task is moved from the root to a child of another task.

**To Reproduce**
1. Define a project with
 -a root task without a child task
 -a root task with a child task
3. Move the root task to a child of another task
4. See the error

**Expected behavior**
The node should not be overlapped.

**Screenshots**
None

**Environment (please complete the following information):**

**Additional context**

**Comment by pvisionjp** [comment]
Fixed in 1.15.1
