### ISSUE TITLE
Sync: Unnecessary recovery of cards

### ISSUE THREAD

**Issue by chandora** [pvisionjp/redsync#37]
**Describe the bug**
Sync with Redmine attempts to recover cards that are not archived.

**To Reproduce**
1. Specify a list for archive in the settings but do not set the Move to List flag.
2. Execute Sync with Redmine and move cards to the list.
3. Execute Sync with Redmine again.
4. See the error.

**Expected behavior**
Those cards should not be recovered.

**Screenshots**
None

**Environment (please complete the following information):**

**Additional context**

**Comment by pvisionjp** [comment]
Fixed in 1.15.1
