### ISSUE TITLE
Gantt: Incorrect sort with missing start date on issue

### ISSUE THREAD

**Issue by chandora** [pvisionjp/redsync#38]
**Describe the bug**
An issue is not sorted correctly when it does not have a start date.

**To Reproduce**
1. Define an issue without a start date and other issues with a start date in Redmine.
2. Open the Gantt chart on Trello.
3. See the error.

**Expected behavior**
An issue should be sorted by the due date if there is no start date.

**Screenshots**
None

**Environment (please complete the following information):**

**Additional context**

**Comment by pvisionjp** [comment]
Fixed in 1.15.2
