### ISSUE TITLE
Settings: Label for exclude links with locked prefix

### ISSUE THREAD

**Issue by chandora** [pvisionjp/redsync#39]
**Describe the bug**
The label for the "exclude links to" section has a prefix with a locked key.

**To Reproduce**
1. Open the Settings
2. Check the Sync on Card section for the "exclude links to" section label
4. See the error

**Expected behavior**
The label should not have any prefixes since the feature is for the free plan.

**Screenshots**
None

**Environment (please complete the following information):**

**Additional context**

**Comment by pvisionjp** [comment]
Fixed in 1.15.2
