### ISSUE TITLE
Custom Fileds for Objects Other Than Issues Still Selectable

### ISSUE THREAD

**Issue by chandora** [pvisionjp/redsync#4]
**Describe the bug**
Custom Fields are selectable in the setting screen when they are created for an object other than issues.

**To Reproduce**
1. Create a Custom Field for an object other than issues (e.g. project)
1. Go to 'Settings'
2. Click on the 'Advanced Settings' tab, then the 'Select' button.
3. Check the Dropdown list
4. See custom fields for other than issues

**Expected behavior**
Custom Fields for objects other than issues should not be included in the dropdown list.

**Screenshots**
N/A

**Environment (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by pvisionjp** [comment]
Fixed in 1.4.0

**Comment by pvisionjp** [comment]
Fixe in 1.4.0
