### ISSUE TITLE
Sync with Redmine: Sync an assigned user from Redmine to Trello

### ISSUE THREAD

**Issue by chandora** [pvisionjp/redsync#43]
**Is your feature request related to a problem? Please describe.**
Sync with Redmine does not sync an assigned user on an Issue to a Card, so I need to assign a user manually.

**Describe the solution you'd like**
Sync an assigned user from an Issue to a Card.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by pvisionjp** [comment]
Supported in 1.17.0
