### ISSUE TITLE
Question: Can this tool sync with Trello issues from Redmine´s children projects

### ISSUE THREAD

**Issue by kevinnaranjoruano** [pvisionjp/redsync#46]
I have a parent project in Redmine with three child projects. In powe-up configuration I chose the parent project, but when I sync data from Redmine its only brings the issues in the parent project, none from the childs projects. 

Is this the expected behaviour ? Do I have to configure anything ? Does the tool support this feature ?

Thanks in advance !

**Comment by pvisionjp** [comment]
Hello @kevinnaranjoruano ,

Thank you for being interested in RedSync.
Currently, RedSync does not support syncing sub-projects.
Sorry, I should have documented this as a restriction.

However, it has been on the enhancement list and I can work on it.
Could you help me to validate the use cases?

I have defined the following use cases:
* RedSync creates all cards on the same list for issues from sub-projects and the main project.
* RedSync shows the sub-project name in the Redmine Data section on a card.
* In Settings, RedSync provides a flag to enable the syncing of sub-projects.

Do they meet your needs?
Do you want to see the cards from sub-projects in different ways? If yes, how?

If the above use cases are okay (at least as a starting point), I will be able to implement them in a week or so, except for the Gantt chart, which would require more work. 

I would appreciate your opinion.

Best regards,
Tateo

**Comment by kevinnaranjoruano** [comment]
Hi !

Thank you for the fast answer and this tool.

I consider the presented use cases are a good starting point, it covers my needs.
I would like to see cards from sub-projects in the same way as the ones for the main project 

Perhaps it would be useful to have the project name in the title or description of the card. That would allow to create some automations in the Trello dashboard. For example, moving cards to different lists based on their project. If this is already possible, my apologies. I have been without using trello for a long time

I take this opportunity to launch a new question: Have you ever thought about the possibility of syncing more than one project at a time ? Would it be technically feasible ?

I really appreciate your work,
Thank you for your consideration,
Best regards

**Comment by pvisionjp** [comment]
Hi,

Thank you for the feedback and suggestions.

I will proceed with implementing those use cases. Please wait for a while.

I think your idea of using the project name as a trigger for automation is excellent. 
One option is to map the project name to a custom field. RedSync already supports mapping certain fields like status to a custom field so extending it to map the project name is feasible. The drawback of this approach is that it requires a paid subscription to Trello to use custom fields.

Having the project name in the title or description is technically feasible but I am concerned it may interfere with the existing content of them. I will take some more time to consider it.

> Have you ever thought about the possibility of syncing more than one project at a time? Would it be technically feasible? 

If you mean to sync multiple projects (at the main level) to a single board, I have not thought of the option. I have concerns that mixing tickets from multiple projects on the same board may confuse users.

May I ask the use case behind this question if you have a specific one?

Have a great weekend!
Tateo

**Comment by kevinnaranjoruano** [comment]
Hi !

So glad to hear you will work on it, Thanks !

> I think your idea of using the project name as a trigger for automation is excellent.
One option is to map the project name to a custom field. RedSync already supports mapping certain fields like status to a custom field so extending it to map the project name is feasible. The drawback of this approach is that it requires a paid subscription to Trello to use custom fields.

I had not thought on that. It is a pretty good solution ! 

> May I ask the use case behind this question if you have a specific one?

In my case I have an structure in Redmine like this:

- Project A
- Project B
- Project C
- Project D
  - Project E
  - Project F
  - Project G
  - Project H
  - etc....

My main content is under Project D, so syncing Project D and its subprojects would be awesome, but I can't forguet the others one.

The only way to sync all tickets in one board in thi case would be to have 4 Trello dashboards to sync each project and then use some power-up to sync cards betweens boards, what it means that the price of the RedSync increase.

I hope I explain myselft good enough,

Have a great weekend !
Best regards

**Comment by pvisionjp** [comment]
Hi,

Thank you for the clarification.
I understand your concern about the cost. I wish that Optro could offer a more flexible pricing model.

Syncing with multiple (main) projects is technically feasible but not feasible to implement due to the estimated workload. Sorry.

You may have considered this, but if you have the privilege to modify the project structure, one option is to add a pseudo parent like:

- Big-Boss-Project
    - Project A
    - Project B
    - Project C
    - Project D
         - Project E
         - ...

> The only way to sync all tickets in one board in thi case would be to have 4 Trello dashboards to sync each project and then use some power-up to sync cards betweens boards, what it means that the price of the RedSync increase.

Unfortunately, the above scenario will not work. 

RedSync assumes that a board is associated with a project. When you sync Trello with Redmine, RedSync checks if a card is created from an issue and the issue still exists in the project associated with the board.

If you move a card to another board, RedSync cannot find the issue of the card in the project associated with the board. In that case, RedSync archives the card or moves it to the list for archived.

Best regards,
Tateo

**Comment by pvisionjp** [comment]
Hi @kevinnaranjoruano,

RedSync now supports syncing the issues from sub-projects.

Settings of RedSync provide three options as follows:
- Include Issues from sub-projects
- Exclude Issues from sub-projects
- Follow Redmine Settings

[Release Note](https://github.com/pvisionjp/redsync/wiki/Release-History)

I hope this new feature is helpful for you.

Thank you for your request and for helping me validate the use cases.
Your feedback will always be welcome.

Best regards,
Tateo

**Comment by kevinnaranjoruano** [comment]
Hi !

Huge thanks ! it seems it is working nicely.

There is only one project that is not working for me, I don't know why. This is the error message when I try to sync

![image](https://github.com/pvisionjp/redsync/assets/86834731/11dd2890-ebe0-4abb-bc36-7c0cc7b06e12)

Thanks for your speed ! 

Do you have somethging like buymeacoffe ? or paypal ?

Best regards

**Comment by pvisionjp** [comment]
Hi @kevinnaranjoruano ,

Oops, I'm very sorry for the error.

Could you please help with the problem determination?

In sync with the error, are there some cards synced before getting the error, or is no card synced at all?

Have you configured RedSync to sync the custom fields?
If yes, could you try without the settings for syncing the custom fields?

Did you click the Cancel button during syncing?
It probably doesn't apply to this case, but the Cancel button has a bug that throws an unknown error. I am fixing it.

Could you clear the cache of the browser and retry it?

Sorry for asking many questions.
I would highly appreciate your help.

> Do you have somethging like buymeacoffe ? or paypal ?

I might have one in the future, but not for now.
Anyway, I appreciate your kind thoughts. 

Best regards,
Tateo

**Comment by kevinnaranjoruano** [comment]
Hi !

I started a brand new trello board on a clean browser and the error appears again.

The syncing proccess read succesfully about 15600 issues from redmine and then tried to create 644 new cards in trello. (That is correct)

It created succesfully 140 new cards and then the error showed up and stopped syncing.

I'm not mapping any custom field
I'm not clicking the Cancel button

It seems I found the issue that is causing the error. Some info of it:

- It has a HUGE description (16.000 characters)
- The description has links to another issuess and wiki pages.
- The description has styling (see image)
- It has 36 issues related

![image](https://github.com/pvisionjp/redsync/assets/86834731/b8f963ef-cb08-4f5f-86b9-9c853aa5aa2c)


Maybe Trello cards has a limit and this is too long for it ?
It seems that is the problem. Found this link (https://community.atlassian.com/t5/Trello-questions/Is-there-a-text-limit-in-the-quot-Description-quot-field-of/qaq-p/838401)

I guess the best solution is to cut description when creating Trello cards

Hope this info can help you.
Thanks for your time

Best regards !

**Comment by chandora** [comment]
Hi,

Thank you for the feedback!!
It is VERY informative and helpful for me.
I said, "That's it!" when I read your comment.

I know some of those limitations from the Trello doc, but I was unaware of the limit on the description length. As you suggested, I will need to trim the description.

I will proceed with the investigation, and when I complete the fix, I will report it here.

> Can you see the image ?

Yes, I can see the image.

Best regards,
Tateo

**Comment by pvisionjp** [comment]
Hi,

I fixed the problem that RedSync cannot sync the issue with a long description. It now truncates the long description to 16,000 chars.

I opened a defect: [Defect #49](https://github.com/pvisionjp/redsync/issues/49)

I would appreciate you check it with your project.

Best regards,
Tateo

**Comment by kevinnaranjoruano** [comment]
Hi !

Glad to say it worked nicely !

![image](https://github.com/pvisionjp/redsync/assets/86834731/bc406417-4d35-4826-a8ba-65796262622d)

Thanks for your amazing job !

Best regards !

**Comment by pvisionjp** [comment]
Hi,

Thank you for your feedback.
You are a great help!

I hope RedSync will be helpful for your project.

Best regards,
Tateo
