### ISSUE TITLE
Gantt: Edit Issues

### ISSUE THREAD

**Issue by chandora** [pvisionjp/redsync#47]
**Is your feature request related to a problem? Please describe.**
There is no way to edit issues on the Gantt chart.

**Describe the solution you'd like**
RedSync should provide a pop-up menu to open an issue and edit it. Same with creating an issue on the Gantt chart.

**Describe alternatives you've considered**
Provide a link to the issue in Redmine. This allows a user to open the issue in Redmine and edit it directly.

**Additional context**
None

**Comment by pvisionjp** [comment]
Supported in 1.19.0
