### ISSUE TITLE
Gantt: Drag a bar with changing the delay to a proceeding issue

### ISSUE THREAD

**Issue by chandora** [pvisionjp/redsync#48]
**Is your feature request related to a problem? Please describe.**
When an issue has a preceding issue with delay, there are restrictions on moving or changing the issue schedule.

**Describe the solution you'd like**
Allow a user to move or change the issue's schedule ignoring the delay and set a new delay after completion.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by pvisionjp** [comment]
Supported in 1.20.0
