### ISSUE TITLE
Custom Fields Not Assinged to Project Still Selectable

### ISSUE THREAD

**Issue by chandora** [pvisionjp/redsync#5]
**Describe the bug**
Custom Fields are selectable in the settings when they are not assigned to the project.

**To Reproduce**
1. Create a Custom Field and assign it to a project other than the target.
2. Edit Power-Up -> Advanced Settings -> Select
3. Check the dropdown
4. See the Custom Field not assigned to the current project.

**Expected behavior**
The custom field should not be included in the selectable one.

**Screenshots**
N/A

**Environment (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by pvisionjp** [comment]
Redmine API does not give the information on which project the custom field is assigned. Hence it is a restriction and should be described in the user guide.

**Comment by pvisionjp** [comment]
Fixed in 1.4.0
