### ISSUE TITLE
Cannot Sync Custom Field from Redmine To Trello when JSONP Enabled

### ISSUE THREAD

**Issue by chandora** [pvisionjp/redsync#6]
**Describe the bug**
A custom field cannot be synced from Redmine to Trello when JSONP is enabled.

**To Reproduce**
1. Define custom field mapping from Redmine to Trello
2. Do Sync with Redmine
3. Check the Card containing the updated custom field
4. Custom field is not updated.

**Expected behavior**
A custom field should be synced from Redmine to Trello.

**Screenshots**
N/A

**Environment (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by pvisionjp** [comment]
Fixed in 1.4.0
